---
output: html_document
---
# header
## header
### header
#### header

**x**
__x__

|column1|column2|colume3|
|:------|------:|:------:|
|left   |right  | center |
|row2|row2|row2|


```{r fig.height=3,fig.width=4,fig.cap="Boxplot of Diamond etc", echo=FALSE}
# require packages
require(ggplot2,quietly=TRUE)

#### boxplot
qplot(cut,price,data=diamonds,geom="boxplot")

```

one explanation for this unexpected finding is that ideal cut diamonds also tend to be **smaller**.  
the mean is \(E(carat | cut=Ideal) = `r mean(subset(diamonds,cut="Ideal")$carat)`\), and size is related to price.

```{r echo =FALSE}
summary(lm(price ~ carat,data=diamonds))
```
```{r echo =FALSE}
library(knitr)
kable(table(diamonds$cut,diamonds$color),format="markdown")
```

|          |    D|    E|    F|    G|    H|    I|   J|
|:---------|----:|----:|----:|----:|----:|----:|---:|
|Fair      |  163|  224|  312|  314|  303|  175| 119|
|Good      |  662|  933|  909|  871|  702|  522| 307|
|Very Good | 1513| 2400| 2164| 2299| 1824| 1204| 678|
|Premium   | 1603| 2337| 2331| 2924| 2360| 1428| 808|
|Ideal     | 2834| 3903| 3826| 4884| 3115| 2093| 896|
> ```


